lint.select = ["E", "F", "B", "W", "I" ,"UP", "ANN", "BLE", "FBT", "A", "COM", "C4", "DTZ", "PIE", "Q", "RET", "SIM", "PL", "RUF"]
lint.extend-select = ["I"]
lint.fixable = ["ALL"]
lint.ignore = [
    "A001", "A002", "A003",
    "B007", "B012", "B018", "B020", "B023", "B008", "B904",
    "BLE001",
    "COM812",
    "DTZ005",
    "F401", "F403", "F405", "E721", "E722", "E731", "E741", "F811", "F821",
    "FBT001", "FBT002", "FBT003",
    "ANN001", "ANN002", "ANN003", "ANN101", "ANN102", "ANN201", "ANN202", "ANN204", "ANN205", "ANN206", "ANN401",
    "E501",
    "PLR2004", "PLR5501", "PLR0913", "PLR0915", "PLR0206", "PLR0911", "PLR0912",
    "PLW0127", "PLW2901", "PLW0602", "PLW0603",
    "PLE0604",
    "RET505", "RET506", "RET507", "RET508",
    "RUF012",
    "SIM102", "SIM117", "SIM113", "SIM114", "SIM115"
]
line-length = 120
target-version = "py37"